import { describe, expect, it } from 'vitest';
import { calculateInfluence, calculateVelocity, initialInteractionState, mapStateToTypography, mapStateToUniforms, normalizePointer, normalizeScroll, reduceInteractionState } from './interaction';
describe('procedural type field interaction contract',()=>{
 it('normalizes and clamps pointer, scroll, and velocity input',()=>{expect(normalizePointer(150,-20,{left:0,top:0,width:100,height:100})).toEqual({x:1,y:1});expect(normalizeScroll(1000,500,500)).toBe(0);expect(calculateVelocity({x:10,y:-10},{x:0,y:0},1)).toEqual({x:1,y:-1})});
 it('calculates bounded local influence',()=>{expect(calculateInfluence({x:.5,y:.5},{x:.5,y:.5},.3)).toBe(1);expect(calculateInfluence({x:0,y:0},{x:1,y:1},.3)).toBe(0)});
 it('moves through pointer, settling, and rest deterministically',()=>{let state=reduceInteractionState(initialInteractionState(),{type:'POINTER',point:{x:.8,y:.2},velocity:{x:.2,y:0}});expect(state.mode).toBe('POINTER_ACTIVE');expect(state.energy).toBeGreaterThan(0);state=reduceInteractionState(state,{type:'RELEASE'});expect(state.mode).toBe('SETTLING');state=reduceInteractionState(state,{type:'TICK',delta:2000,time:2000});expect(state.mode).toBe('REST');expect(state.energy).toBe(0)});
 it('gives touch precedence and maps mobile scroll to bounded energy',()=>{let state=reduceInteractionState(initialInteractionState(),{type:'SCROLL',progress:.5,velocity:8});expect(state.mode).toBe('SCROLL_ACTIVE');expect(state.energy).toBe(1);state=reduceInteractionState(state,{type:'TOUCH',point:{x:.1,y:.2},velocity:{x:0,y:0}});expect(state.mode).toBe('TOUCH_ACTIVE');expect(state.source).toBe('touch')});
 it('makes reduced motion meaningful in both render mappings',()=>{const state=reduceInteractionState({...initialInteractionState(),energy:1},{type:'REDUCED_MOTION',enabled:true});expect(state.mode).toBe('REDUCED_MOTION');expect(mapStateToTypography(state).translateX).toBe(0);expect(mapStateToUniforms(state).energy).toBe(0);expect(mapStateToUniforms(state).time).toBe(0)});
 it('clamps resize normalization and uniform values',()=>{let state=reduceInteractionState(initialInteractionState(),{type:'RESIZE',aspect:99});state={...state,energy:99,influenceRadius:-1,scrollProgress:4};const uniforms=mapStateToUniforms(state);expect(state.aspect).toBe(3);expect(uniforms.energy).toBe(1);expect(uniforms.radius).toBe(.05);expect(uniforms.phase).toBe(1)});
});
