import { useEffect, useRef } from 'react';
import { calculateVelocity, initialInteractionState, mapStateToTypography, normalizePointer, normalizeScroll, reduceInteractionState, type InteractionState } from './interaction';
import { ShaderSurface } from './ShaderSurface';
export function ProceduralTypeField(){const rootRef=useRef<HTMLElement>(null),typeRef=useRef<HTMLHeadingElement>(null),diagnosticRef=useRef<HTMLOutputElement>(null),stateRef=useRef<InteractionState>(initialInteractionState());useEffect(()=>{const root=rootRef.current;if(!root)return;const media=matchMedia('(prefers-reduced-motion: reduce)');stateRef.current=initialInteractionState(media.matches);let previous=stateRef.current.pointer,last=performance.now(),frame=0,visible=true;
const present=()=>{const state=stateRef.current,visual=mapStateToTypography(state);root.dataset.mode=state.mode;root.style.setProperty('--field-energy',state.energy.toFixed(3));if(typeRef.current){typeRef.current.style.setProperty('--type-x',`${visual.translateX}px`);typeRef.current.style.setProperty('--type-y',`${visual.translateY}px`);typeRef.current.style.setProperty('--type-scale-x',`${visual.scaleX}`);typeRef.current.style.setProperty('--type-scale-y',`${visual.scaleY}`);typeRef.current.style.setProperty('--type-skew',`${visual.skew}deg`);typeRef.current.style.setProperty('--type-track',`${visual.tracking}em`)}if(diagnosticRef.current)diagnosticRef.current.value=`MODE ${state.mode} · ENERGY ${state.energy.toFixed(2)} · SOURCE ${state.source}`};
const loop=(now:number)=>{if(visible){stateRef.current=reduceInteractionState(stateRef.current,{type:'TICK',delta:now-last,time:now});present()}last=now;frame=requestAnimationFrame(loop)};
const point=(event:PointerEvent)=>{const next=normalizePointer(event.clientX,event.clientY,root.getBoundingClientRect()),velocity=calculateVelocity(next,previous,performance.now()-last);previous=next;stateRef.current=reduceInteractionState(stateRef.current,{type:event.pointerType==='touch'?'TOUCH':'POINTER',point:next,velocity});present()};
const release=()=>{stateRef.current=reduceInteractionState(stateRef.current,{type:'RELEASE'});present()};let scrollY=window.scrollY,scrollTime=performance.now();const scroll=()=>{if(matchMedia('(max-width: 720px)').matches){const now=performance.now(),rect=root.getBoundingClientRect(),progress=normalizeScroll(rect.top,rect.height,innerHeight),velocity=(window.scrollY-scrollY)/Math.max(1,now-scrollTime)/2;stateRef.current=reduceInteractionState(stateRef.current,{type:'SCROLL',progress,velocity});scrollY=window.scrollY;scrollTime=now;present()}};
const resize=()=>{stateRef.current=reduceInteractionState(stateRef.current,{type:'RESIZE',aspect:root.clientWidth/Math.max(1,root.clientHeight)})},motion=()=>{stateRef.current=reduceInteractionState(stateRef.current,{type:'REDUCED_MOTION',enabled:media.matches});present()};const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});observer.observe(root);root.addEventListener('pointermove',point);root.addEventListener('pointerleave',release);root.addEventListener('pointerup',release);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',resize);media.addEventListener('change',motion);resize();present();frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);observer.disconnect();root.removeEventListener('pointermove',point);root.removeEventListener('pointerleave',release);root.removeEventListener('pointerup',release);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',resize);media.removeEventListener('change',motion)}},[]);
return <section ref={rootRef} className="procedural-type-field specimen-card" data-cy="procedural-type-field" data-mode="REST" aria-labelledby="procedural-type-title"><ShaderSurface stateRef={stateRef}/><div className="type-field-grid" aria-hidden="true"/><div className="type-field-content"><span className="type-field-kicker">SPECIMEN 002 / LIVE INPUT MATERIAL</span><h1 ref={typeRef} id="procedural-type-title"><span>TYPE</span><span>HAS A</span><span className="type-field-accent">PULSE.</span></h1><p>Semantic typography and a chromatic GPU field move from one deterministic interaction state. Move to excite. Leave to settle. Scroll on mobile.</p><output ref={diagnosticRef} className="type-field-diagnostic" data-cy="type-field-diagnostic" aria-live="polite">MODE REST · ENERGY 0.00 · SOURCE none</output></div></section>}
